export const awards = [
  {
    name: "Interactive Experience",
    type: "Winner",
    project: "Digital Horizons 2024",
    label: "Awwwards",
  },
  {
    name: "Site of the month",
    type: "Awwwards",
    project: "Nexus Creative Studio",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Ethereal Designs",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Quantum Labs",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Midnight Studios",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Aurora Interactive",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Prism Portfolio",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Velocity Agency",
    label: "Vacuum",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Zenith Creative",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Flux Design Co",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Catalyst Studios",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Nexus Creative Studio",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Ethereal Designs",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Quantum Labs",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Midnight Studios",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Aurora Interactive",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Prism Portfolio",
    label: "See Live",
  },
];
